version: '2.1'
orbs:
  snyk: snyk/snyk@1.4.0
  
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
      
workflows:
  build-test-snyk:
    jobs:
      - snyk-scan:
          fail-on-issues: false
          monitor-on-build: true
