version: '2.1'
orbs:
  snyk: snyk/snyk@1.2.0
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm install
      - run: npm ci
      - snyk/scan:
          token-variable: API_TOKEN
          fail-on-issues: false
workflows: null
