version: '2.1'
orbs:
  snyk: snyk/snyk@1.2.0
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - snyk/scan
          fail-on-issues: false
          severity-threshold: high
          token-variable: API_TOKEN
      
workflows: null
